"""
ReAgent Sydney - Agent Performance Monitoring

Comprehensive monitoring for individual agent performance, including execution times,
success rates, resource usage, and business outcome tracking.
"""

import time
import asyncio
import psutil
import threading
from typing import Dict, Any, List, Optional, Callable
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from collections import defaultdict, deque
logger = get_logger(__name__)

# =================================================================
# AGENT-SPECIFIC METRICS
# =================================================================

# Agent execution tracking
agent_execution_start_time = Gauge(
    'agent_execution_start_time',
    'Timestamp when agent execution started',
    ['agent_name', 'execution_id']
)

agent_execution_memory_peak_bytes = Gauge(
    'agent_execution_memory_peak_bytes',
    'Peak memory usage during agent execution',
    ['agent_name', 'execution_type']
)

agent_cpu_usage_percent = Gauge(
    'agent_cpu_usage_percent',
    'CPU usage percentage by agent',
    ['agent_name']
)

agent_task_queue_length = Gauge(
    'agent_task_queue_length',
    'Number of tasks in agent queue',
    ['agent_name', 'priority']
)

agent_decision_quality_score = Gauge(
    'agent_decision_quality_score',
    'Quality score for agent decisions (0-1)',
    ['agent_name', 'decision_type']
)

# Agent coordination metrics
agent_handoff_success_rate = Gauge(
    'agent_handoff_success_rate',
    'Success rate of agent-to-agent handoffs',
    ['from_agent', 'to_agent']
)

agent_data_dependency_wait_seconds = Histogram(
    'agent_data_dependency_wait_seconds',
    'Time waiting for data dependencies',
    ['agent_name', 'dependency_type'],
    buckets=[0.1, 0.5, 1.0, 5.0, 10.0, 30.0, 60.0, float('inf')]
)

# Business outcome tracking per agent
agent_business_outcome_value = Gauge(
    'agent_business_outcome_value',
    'Business value generated by agent',
    ['agent_name', 'outcome_type', 'measurement_unit']
)

agent_prediction_accuracy = Gauge(
    'agent_prediction_accuracy',
    'Accuracy of agent predictions over time',
    ['agent_name', 'prediction_type']
)

# =================================================================
# AGENT PERFORMANCE DATA STRUCTURES
# =================================================================

@dataclass
class AgentExecutionMetrics:
    """Metrics for a single agent execution."""
    agent_name: str
    execution_id: str
    start_time: float
    end_time: Optional[float] = None
    duration_seconds: Optional[float] = None
    memory_usage_mb: Optional[float] = None
    cpu_usage_percent: Optional[float] = None
    status: str = "running"  # running, completed, failed, timeout
    error_message: Optional[str] = None
    business_outcomes: Dict[str, Any] = field(default_factory=dict)
    resource_peaks: Dict[str, float] = field(default_factory=dict)

@dataclass
class AgentPerformanceWindow:
    """Performance metrics over a time window."""
    window_start: float
    window_end: float
    execution_count: int = 0
    success_count: int = 0
    failure_count: int = 0
    total_duration: float = 0.0
    average_duration: float = 0.0
    peak_memory_mb: float = 0.0
    average_cpu_percent: float = 0.0
    business_value_generated: float = 0.0

class AgentMonitor:
    """Real-time monitoring for individual agents."""
    
    def __init__(self, agent_name: str):
        self.agent_name = agent_name
        self.current_executions: Dict[str, AgentExecutionMetrics] = {}
        self.execution_history: deque = deque(maxlen=1000)  # Keep last 1000 executions
        self.performance_windows: List[AgentPerformanceWindow] = []
        self.resource_monitor_thread: Optional[threading.Thread] = None
        self.monitoring_active = False
        self._lock = threading.Lock()
        
    def start_execution_monitoring(self, execution_id: str, execution_type: str = "default") -> str:
        """Start monitoring an agent execution."""
        with self._lock:
            metrics = AgentExecutionMetrics(
                agent_name=self.agent_name,
                execution_id=execution_id,
                start_time=time.time()
            )
            
            self.current_executions[execution_id] = metrics
            
            # Update Prometheus metrics
            agent_execution_start_time.labels(
                agent_name=self.agent_name,
                execution_id=execution_id
            ).set(metrics.start_time)
            
            # Start resource monitoring for this execution
            self._start_resource_monitoring(execution_id)
            
            logger.info(
                "Started execution monitoring",
                agent_name=self.agent_name,
                execution_id=execution_id,
                execution_type=execution_type
            )
            
            return execution_id
    
    def end_execution_monitoring(self, execution_id: str, status: str = "completed", 
                               error_message: str = None, business_outcomes: Dict[str, Any] = None):
        """End monitoring for an agent execution."""
        with self._lock:
            if execution_id not in self.current_executions:
                logger.warning(
                    "Attempted to end monitoring for unknown execution",
                    agent_name=self.agent_name,
                    execution_id=execution_id
                )
                return
                
            metrics = self.current_executions[execution_id]
            metrics.end_time = time.time()
            metrics.duration_seconds = metrics.end_time - metrics.start_time
            metrics.status = status
            metrics.error_message = error_message
            
            if business_outcomes:
                metrics.business_outcomes = business_outcomes
                
            # Stop resource monitoring
            self._stop_resource_monitoring(execution_id)
            
            # Move to history
            self.execution_history.append(metrics)
            del self.current_executions[execution_id]
            
            # Update Prometheus metrics
            from .metrics import agent_execution_duration_seconds, agent_executions_total
            
            agent_execution_duration_seconds.labels(
                agent_name=self.agent_name,
                execution_type="default"
            ).observe(metrics.duration_seconds)
            
            agent_executions_total.labels(
                agent_name=self.agent_name,
                status=status
            ).inc()
            
            # Update business outcome metrics
            if business_outcomes:
                for outcome_type, value in business_outcomes.items():
                    if isinstance(value, (int, float)):
                        agent_business_outcome_value.labels(
                            agent_name=self.agent_name,
                            outcome_type=outcome_type,
                            measurement_unit="count"
                        ).set(value)
            
            logger.info(
                "Completed execution monitoring",
                agent_name=self.agent_name,
                execution_id=execution_id,
                duration_seconds=metrics.duration_seconds,
                status=status,
                business_outcomes=business_outcomes
            )
    
    def _start_resource_monitoring(self, execution_id: str):
        """Start monitoring system resources for an execution."""
        def monitor_resources():
            process = psutil.Process()
            max_memory = 0
            cpu_samples = []
            
            while execution_id in self.current_executions:
                try:
                    # Memory monitoring
                    memory_info = process.memory_info()
                    memory_mb = memory_info.rss / 1024 / 1024
                    max_memory = max(max_memory, memory_mb)
                    
                    # CPU monitoring
                    cpu_percent = process.cpu_percent(interval=0.1)
                    cpu_samples.append(cpu_percent)
                    
                    # Update metrics
                    with self._lock:
                        if execution_id in self.current_executions:
                            metrics = self.current_executions[execution_id]
                            metrics.memory_usage_mb = memory_mb
                            metrics.cpu_usage_percent = cpu_percent
                            metrics.resource_peaks['memory_mb'] = max_memory
                            metrics.resource_peaks['cpu_percent'] = max(cpu_samples) if cpu_samples else 0
                    
                    # Update Prometheus gauges
                    agent_execution_memory_peak_bytes.labels(
                        agent_name=self.agent_name,
                        execution_type="default"
                    ).set(max_memory * 1024 * 1024)
                    
                    agent_cpu_usage_percent.labels(
                        agent_name=self.agent_name
                    ).set(cpu_percent)
                    
                    time.sleep(1)  # Sample every second
                    
                except (psutil.NoSuchProcess, KeyError):
                    break
                except Exception as e:
                    logger.error(
                        "Error monitoring resources",
                        agent_name=self.agent_name,
                        execution_id=execution_id,
                        error=str(e)
                    )
                    break
        
        monitor_thread = threading.Thread(target=monitor_resources, daemon=True)
        monitor_thread.start()
    
    def _stop_resource_monitoring(self, execution_id: str):
        """Stop resource monitoring for an execution."""
        # Resource monitoring will stop automatically when execution_id is removed
        pass
    
    def get_current_performance(self) -> Dict[str, Any]:
        """Get current performance metrics for the agent."""
        with self._lock:
            active_executions = len(self.current_executions)
            recent_executions = list(self.execution_history)[-10:]  # Last 10 executions
            
            # Calculate recent performance
            if recent_executions:
                success_count = sum(1 for exec in recent_executions if exec.status == "completed")
                total_duration = sum(exec.duration_seconds for exec in recent_executions if exec.duration_seconds)
                avg_duration = total_duration / len(recent_executions) if recent_executions else 0
                success_rate = success_count / len(recent_executions)
                
                avg_memory = sum(
                    exec.resource_peaks.get('memory_mb', 0) 
                    for exec in recent_executions
                ) / len(recent_executions)
                
                avg_cpu = sum(
                    exec.resource_peaks.get('cpu_percent', 0)
                    for exec in recent_executions  
                ) / len(recent_executions)
            else:
                avg_duration = 0
                success_rate = 0
                avg_memory = 0
                avg_cpu = 0
            
            return {
                "agent_name": self.agent_name,
                "timestamp": time.time(),
                "active_executions": active_executions,
                "recent_performance": {
                    "executions_last_10": len(recent_executions),
                    "success_rate": success_rate,
                    "average_duration_seconds": avg_duration,
                    "average_memory_mb": avg_memory,
                    "average_cpu_percent": avg_cpu
                },
                "total_executions": len(self.execution_history),
                "current_queue_length": self._get_queue_length()
            }
    
    def _get_queue_length(self) -> int:
        """Get current task queue length (would integrate with actual queue)."""
        # This would integrate with the actual task queue system
        return 0
    
    def record_business_outcome(self, outcome_type: str, value: float, 
                              measurement_unit: str = "count"):
        """Record a business outcome for this agent."""
        agent_business_outcome_value.labels(
            agent_name=self.agent_name,
            outcome_type=outcome_type,
            measurement_unit=measurement_unit
        ).set(value)
        
        logger.info(
            "Recorded business outcome",
            agent_name=self.agent_name,
            outcome_type=outcome_type,
            value=value,
            unit=measurement_unit
        )
    
    def update_prediction_accuracy(self, prediction_type: str, accuracy: float):
        """Update prediction accuracy metrics."""
        agent_prediction_accuracy.labels(
            agent_name=self.agent_name,
            prediction_type=prediction_type
        ).set(accuracy)
        
        logger.info(
            "Updated prediction accuracy",
            agent_name=self.agent_name,
            prediction_type=prediction_type,
            accuracy=accuracy
        )

# =================================================================
# GLOBAL AGENT MONITORING SYSTEM
# =================================================================

class GlobalAgentMonitor:
    """Global monitoring system for all agents."""
    
    def __init__(self):
        self.agent_monitors: Dict[str, AgentMonitor] = {}
        self.system_health_check_interval = 60  # seconds
        self.health_check_thread: Optional[threading.Thread] = None
        self.running = False
        
    def get_agent_monitor(self, agent_name: str) -> AgentMonitor:
        """Get or create an agent monitor."""
        if agent_name not in self.agent_monitors:
            self.agent_monitors[agent_name] = AgentMonitor(agent_name)
        return self.agent_monitors[agent_name]
    
    def start_global_monitoring(self):
        """Start global monitoring system."""
        self.running = True
        
        def health_check_loop():
            while self.running:
                try:
                    self._update_global_metrics()
                    time.sleep(self.system_health_check_interval)
                except Exception as e:
                    logger.error("Error in global monitoring loop", error=str(e), exc_info=True)
        
        self.health_check_thread = threading.Thread(target=health_check_loop, daemon=True)
        self.health_check_thread.start()
        
        logger.info("Started global agent monitoring system")
    
    def stop_global_monitoring(self):
        """Stop global monitoring system."""
        self.running = False
        if self.health_check_thread:
            self.health_check_thread.join(timeout=5)
        
        logger.info("Stopped global agent monitoring system")
    
    def _update_global_metrics(self):
        """Update global monitoring metrics."""
        total_active_executions = 0
        total_agents = len(self.agent_monitors)
        
        for agent_name, monitor in self.agent_monitors.items():
            performance = monitor.get_current_performance()
            total_active_executions += performance["active_executions"]
            
            # Update global metrics
            agent_task_queue_length.labels(
                agent_name=agent_name,
                priority="normal"
            ).set(performance["current_queue_length"])
        
        logger.debug(
            "Updated global agent metrics",
            total_agents=total_agents,
            total_active_executions=total_active_executions
        )
    
    def get_system_overview(self) -> Dict[str, Any]:
        """Get overview of all agent performance."""
        overview = {
            "timestamp": time.time(),
            "total_agents": len(self.agent_monitors),
            "agents": {}
        }
        
        for agent_name, monitor in self.agent_monitors.items():
            overview["agents"][agent_name] = monitor.get_current_performance()
        
        return overview
    
    def get_performance_summary(self, time_window_minutes: int = 60) -> Dict[str, Any]:
        """Get performance summary for all agents over a time window."""
        cutoff_time = time.time() - (time_window_minutes * 60)
        
        summary = {
            "time_window_minutes": time_window_minutes,
            "summary_timestamp": time.time(),
            "agents": {}
        }
        
        for agent_name, monitor in self.agent_monitors.items():
            # Filter executions within time window
            recent_executions = [
                exec for exec in monitor.execution_history
                if exec.start_time >= cutoff_time
            ]
            
            if recent_executions:
                success_count = sum(1 for exec in recent_executions if exec.status == "completed")
                total_duration = sum(exec.duration_seconds for exec in recent_executions if exec.duration_seconds)
                
                summary["agents"][agent_name] = {
                    "executions": len(recent_executions),
                    "success_rate": success_count / len(recent_executions),
                    "average_duration": total_duration / len(recent_executions),
                    "total_business_value": sum(
                        sum(exec.business_outcomes.values()) if exec.business_outcomes else 0
                        for exec in recent_executions
                    )
                }
            else:
                summary["agents"][agent_name] = {
                    "executions": 0,
                    "success_rate": 0,
                    "average_duration": 0,
                    "total_business_value": 0
                }
        
        return summary

# Global instance
global_agent_monitor = GlobalAgentMonitor()

# Convenience functions
def get_agent_monitor(agent_name: str) -> AgentMonitor:
    """Get agent monitor for a specific agent."""
    return global_agent_monitor.get_agent_monitor(agent_name)

def start_monitoring():
    """Start the global monitoring system."""
    global_agent_monitor.start_global_monitoring()

def stop_monitoring():
    """Stop the global monitoring system."""
    global_agent_monitor.stop_global_monitoring()